# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29974d3090c415b620cd1a130a76b8403d6f1571f51fc71563c4d8527357e96ad1d705da8ba2389a1e0056e64c8ab784a36baf0deb77d26e9f1c2b561972636d

test:
  secret_key_base: 803fc0d3f8a128618bf47af451f88ca38a280ff25d1ba5554123f1cddc22af39d6d401e4a1c8121cfdebe1ef21c5cd19e4776e0d3b461c6df5d24411e3aec2c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
